### ISSUE TITLE
sx127x lib broken

### ISSUE THREAD

**Issue by olliw42** [olliw42/sx12xx-lib#12]
@jlpoltrack 
I was just trying to updat ethe upstream mLRS code to the latest verions of this lib here ... and found quite a number of issues with.

Not only that it gives a number of compile errors within the lib istelf (i.e. not in the outside upstream code)(thes PR was obviously not checked to compiled before merge), but it raises also a number of more fundamental issues. This we merged a bit too hastingly. 

- https://github.com/olliw42/sx12xx-lib/blob/main/src/sx127x.h#L237: '_' missing
- https://github.com/olliw42/sx12xx-lib/blob/main/src/sx127x.h#L240: duplication
- https://github.com/olliw42/sx12xx-lib/blob/main/src/sx127x.cpp#L222: LORA and REG swapped
- now the fundamental issue: WriteBuffer(), ReadBuffer(), GetStatus() need specifically lora registers but by their nature are supposed to be general handlers ... at least - if I'm not mistaken - for the other sx128x and sx126x libs these functions work for both Lora and FLRC/GFSK modes ... with looking myself into teh datasheet I' not sure what to make of this ...

:)

**Comment by jlpoltrack** [comment]
I will submit another PR for the three issues highlighted - my bad.

For those functions, I see in the datasheet that this buffer is specific to LoRa (phrasing 'uniquely accessible'):

<img width="1298" alt="image" src="https://github.com/olliw42/sx12xx-lib/assets/41841496/f8727954-215a-4dd1-acd6-725370b2cece">

The FSK FIFO is mentioned in this section and seems to function rather differently:

<img width="600" alt="image" src="https://github.com/olliw42/sx12xx-lib/assets/41841496/746bb425-9783-4724-9d60-c0839aded15a">

SX126x + SX128x seem much simpler in design when comparing :)

**Comment by olliw42** [comment]
doesn't this suggest that there will be relatively massive changes needed also upstream?

I have a feeling that here we need to follow a different approach, i.e., that in a branch somewhere a full compiling&working implementation is attempted, so we can see what is actually all needed. This looks a bit to me like stirring in the dark at the moment.

I'm unclined to suggest that the last pr is reverted, to not break upstream, and then work it all out in another place.

**Comment by jlpoltrack** [comment]
> I'm unclined to suggest that the last pr is reverted, to not break upstream, and then work it all out in another place.

I think that this makes the most sense.

I wonder if it makes sense to not try FSK for SX127x.  Looking more into the datasheet I see a few further issues:

- FSK FIFO is only 64 bytes, smaller than mLRS payload
- DIO1, DIO2 and DIO3 are used to understand the FIFO state and aren't available in most hardware.

**Comment by olliw42** [comment]
>>   I'm unclined to suggest that the last pr is reverted, to not break upstream, and then work it all out in another place.

> I think that this makes the most sense.

I think it should be possible to fully work it out in the upstream repo, in the sx1276x driver there.

>I wonder if it makes sense to not try FSK for SX127x. Looking more into the datasheet I see a few further issues:
>
>    FSK FIFO is only 64 bytes, smaller than mLRS payload
>    DIO1, DIO2 and DIO3 are used to understand the FIFO state and aren't available in most hardware.

interesting ... I can't comment on it from scratch ... I just know that CrossFire is doing FSK ...

anyway, for now and here, we shoudl revert the last commit
